### ISSUE TITLE
New release needed to incorporate 7ff5528

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/nodeaccess_nodereference#2]
Error: Call to undefined function drupal_static() in nodeaccess_nodereference_get_referenced() (line 227 of /app/docroot/modules/nodeaccess_nodereference/nodeaccess_nodereference.module

I note that you, @herbdool  have actually fixed this in [this commit](https://github.com/backdrop-contrib/nodeaccess_nodereference/commit/7ff55286c6f58face21976ae9cfbc0e14d98a194) but that this was after the release and there hasn't been another release.

**Comment by herbdool** [comment]
Released.
